name: Push to Lokalise on Merge

on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - main  # Trigger on push to main branch
  #   paths:
  #     - 'src/locales/en*.json'  # Only trigger when English source files change
  # pull_request:
  #   types: [closed]
  #   branches:
  #     - main  # Trigger when PR is merged to main
  #   paths:
  #     - 'src/locales/en*.json'

jobs:
  push-to-lokalise:
    runs-on: ubuntu-latest
    # Only run if it's a push to main OR a merged PR (not just closed)
    if: github.ref == 'refs/heads/main' || (github.event.pull_request.merged == true)
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Lokalise CLI
        run: curl -sSL https://raw.githubusercontent.com/lokalise/lokalise-cli-2-go/master/install.sh | sh

      - name: Upload English source files to Lokalise
        run: |
          echo "=== Uploading source files to Lokalise ==="
          
          # Upload en.json (main source file)
          if [ -f "src/locales/en.json" ]; then
            echo "Uploading en.json..."
            ./bin/lokalise2 file upload \
              --token ${{ secrets.LOKALISE_API_TOKEN }} \
              --project-id ${{ secrets.LOKALISE_PROJECT_ID }} \
              --file "src/locales/en.json" \
              --lang-iso en \
              --replace-modified \
              --include-path \
              --distinguish-by-file \
              --tag-inserted-keys \
              --tag-updated-keys \
              --cleanup-mode
            echo "✅ en.json uploaded successfully"
          else
            echo "⚠️ en.json not found"
          fi
          
          # Upload en-US.json if it exists
          if [ -f "src/locales/en-US.json" ]; then
            echo "Uploading en-US.json..."
            ./bin/lokalise2 file upload \
              --token ${{ secrets.LOKALISE_API_TOKEN }} \
              --project-id ${{ secrets.LOKALISE_PROJECT_ID }} \
              --file "src/locales/en-US.json" \
              --lang-iso en-US \
              --replace-modified \
              --include-path \
              --distinguish-by-file \
              --tag-inserted-keys \
              --tag-updated-keys
            echo "✅ en-US.json uploaded successfully"
          else
            echo "ℹ️ en-US.json not found (optional)"
          fi

      - name: Verify upload
        run: |
          echo "=== Verifying upload ==="
          
          # Get project stats
          curl -s -X GET \
            "https://api.lokalise.com/api2/projects/${{ secrets.LOKALISE_PROJECT_ID }}" \
            -H "X-Api-Token: ${{ secrets.LOKALISE_API_TOKEN }}" | \
            jq -r '"Project: \(.project.name) | Keys: \(.project.statistics.keys_total) | Languages: \(.project.statistics.languages_total)"'
          
          # Show recent keys
          echo "Recent keys in project:"
          curl -s -X GET \
            "https://api.lokalise.com/api2/projects/${{ secrets.LOKALISE_PROJECT_ID }}/keys?limit=5" \
            -H "X-Api-Token: ${{ secrets.LOKALISE_API_TOKEN }}" | \
            jq -r '.keys[] | "- \(.key_name.web)"'

      - name: Summary
        run: |
          echo "=== Upload Complete ==="
          echo "✅ Source files pushed to Lokalise"
          echo "🔄 Lokalise automation will now process new/updated keys"
          echo "📝 Run 'Full Auto-Translation Workflow' to get translations back"
          echo ""
          echo "Or wait for the scheduled pull to happen automatically."